/*
    샘플 테이블
*/

CREATE TABLE SAMPLE_T (
    NAME VARCHAR2(20), 
    KOR NUMBER(3), 
    ENG NUMBER(3), 
    MATH NUMBER(3)
);

INSERT INTO SAMPLE_T VALUES ('A', 100, 100, NULL);
INSERT INTO SAMPLE_T VALUES ('B', 100, NULL, 100);
INSERT INTO SAMPLE_T VALUES ('C', NULL, 100, 100);
COMMIT;

-- SAMPLE_T의 전체 데이터 조회
SELECT * 
FROM SAMPLE_T;

-- SAMPLE_T의 전체 데이터와 점수 합계 조회
SELECT NAME, KOR, ENG, MATH, 
    (KOR + ENG + MATH) TOTAL -- NULL이 포함된 연산 결과는 NULL이다.
FROM SAMPLE_T;

/*
    NULL 처리 함수
    1. NVL(EXPR, VALUE IF EXPR IS NULL)
    2. NVL2(EXPR, VALUE IF EXPR IS NOT NULL, VALUE IF EXPR IS NULL)
*/

SELECT NAME, 
    NVL(KOR, 0) + NVL(ENG, 0) + NVL(MATH, 0) 합계 
FROM SAMPLE_T;

-- HR 계정으로 접속하여 사원들의 PAY 조회
SELECT FIRST_NAME, SALARY, COMMISSION_PCT, 
    SALARY + (SALARY * NVL(COMMISSION_PCT, 0)) PAY 
FROM EMPLOYEES;